-- user
CREATE TABLE IF NOT EXISTS users (
   USER_ID integer NOT NULL CONSTRAINT USER_ID PRIMARY KEY,
   USERNAME text NOT NULL,
   FIRST_NAME text NOT NULL,
   LAST_NAME text NOT NULL,
   PASSWD text NOT NULL,
   UNIQUE(USERNAME, PASSWD)
);

-- spending
CREATE TABLE IF NOT EXISTS expense_activity (
   EXPENSE_ID integer NOT NULL CONSTRAINT EXPENSE_ID PRIMARY KEY,
   USER_ID integer NOT NULL,
   ACTIVITY text NOT NULL,
   CREATED_AT text NOT NULL,
   EXPENSE double NOT NULL,
   COMMENT text NOT NULL,
   FOREIGN KEY(USER_ID) REFERENCES users(USER_ID)
);

-- social
CREATE TABLE IF NOT EXISTS friends (
    USER_ID integer NOT NULL CONSTRAINT USER_ID PRIMARY KEY,
    FRIENDS text,
    FOREIGN KEY(USER_ID) REFERENCES users(USER_ID)
);
