-- user
CREATE TABLE IF NOT EXISTS users (
   USER_ID integer NOT NULL CONSTRAINT USER_ID PRIMARY KEY,
   USERNAME text NOT NULL,
   FIRST_NAME text NOT NULL,
   LAST_NAME text NOT NULL,
   PASSWD text NOT NULL,
   UNIQUE(USERNAME, PASSWD)
);

-- expense
CREATE TABLE IF NOT EXISTS expense (
   EXPENSE_ID integer NOT NULL CONSTRAINT EXPENSE_ID PRIMARY KEY,
   EXPENSE_CAT text NOT NULL,
   EXPENSE_SUBCAT text NOT NULL,
   UNIQUE(EXPENSE_CAT, EXPENSE_SUBCAT)
);

-- spending
CREATE TABLE IF NOT EXISTS spending (
   USER_ID integer NOT NULL,
   EXPENSE_ID integer NOT NULL,
   DATE_PURCH text NOT NULL,
   QUANTITY double NOT NULL,
   PRICE double NOT NULL,
   COMMENTS text NOT NULL,
   CONSTRAINT spending_pk PRIMARY KEY (EXPENSE_ID,USER_ID),
   FOREIGN KEY(USER_ID) REFERENCES users(USER_ID),
   FOREIGN KEY(EXPENSE_ID) REFERENCES expense(EXPENSE_ID)
);

-- social
CREATE TABLE IF NOT EXISTS social (
   USER_ID integer NOT NULL CONSTRAINT USER_ID PRIMARY KEY,
   USER_CONNECTION text,
   FOREIGN KEY(USER_ID) REFERENCES users(USER_ID)
);


-- EXAMPLES:
-- users data
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("a544", "Ali", "Tattar", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("b544", "Ben", "Tattar", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("c544", "Anna", "Tattar", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("d544", "Adam", "Thomas", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("e544", "Eve", "Thomas", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("f544", "Zen", "Thomas", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("g544", "Hugo", "Thomas", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("h544", "Victor", "Thomas", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("i544", "Connor", "Thomas", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("j544", "James", "Jimmy", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("k544", "John", "Jimmy", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("l544", "Jamie", "Jimmy", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("m544", "Jayci", "Jimmy", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("n544", "Yucca", "Jimmy", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("o544", "Skinny", "Jimmy", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("p544", "Brown", "June", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("q544", "Tommy", "June", "##########");
INSERT INTO users (USERNAME, FIRST_NAME, LAST_NAME, PASSWD) VALUES ("r544", "Heather", "June", "##########");

-- expense data
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("FOOD", "VEGETABLES");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("FOOD", "MEAT");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("FOOD", "MILK");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("FOOD", "RICE");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("ELECTRONICS", "LAPTOP");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("ELECTRONICS", "TV");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("ELECTRONICS", "MONITOR");
INSERT INTO expense (EXPENSE_CAT, EXPENSE_SUBCAT) VALUES ("LIFESTYLE", "CLOTHES");

